services:
  service-users:
    build: ./users
    ports:
      - "3001:3000"
    restart: always
    environment:
      DB_HOST: users-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: usersdb
      JWT_SECRET: convive_secret
      DB_PORT: 5432
    depends_on:
      - users-db
    networks: [backend]

  users-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - backend

  service-events:
    build: ./events
    restart: always
    environment:
      DB_HOST: events-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: eventsdb
      DB_PORT: 5432
      USERS_API: http://service-users:3000
      SPACES_API: http://service-spaces:3000
      JWT_SECRET: convive_secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - events-db
      - service-users
      - service-spaces
    networks: [backend]

  events-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventsdb
    ports:
      - "5434:5432"
    volumes:
      - events_data:/var/lib/postgresql/data
    networks:
      - backend

  service-auth:
    build: ./auth
    ports:
      - "3002:3000"
    restart: always
    environment:
      USERS_API: http://service-users:3000
      JWT_SECRET: convive_secret
      JWT_EXPIRES_IN: 1d
    depends_on:
      - service-users
    networks: [backend]

  service-spaces:
    build: ./spaces
    ports:
      - "3003:3000"
    restart: always
    environment:
      DB_HOST: spaces-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: spacesdb
      JWT_SECRET: convive_secret
      DB_PORT: 5432
    depends_on:
      - spaces-db
    networks:
      - backend

  spaces-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spacesdb
    ports:
      - "5435:5432"
    volumes:
      - spaces_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks: [backend]

  ngnix:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - service-users
    networks: [backend]

volumes:
  users_data:
  events_data:
  spaces_data:

networks:
  backend:
    driver: bridge
